// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwsvnsqrmvzdhlpxmpbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3c3Zuc3FybXZ6ZGhscHhtcGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzQ5OTEsImV4cCI6MjA3MzQxMDk5MX0.n1NiKZTL8ytz2tgF424bYvvNLjUrBA8JxjcEGAILRr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});